// Code generated by go-swagger; DO NOT EDIT.

package providers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetProvidersCountParams creates a new GetProvidersCountParams object
// with the default values initialized.
func NewGetProvidersCountParams() *GetProvidersCountParams {
	var ()
	return &GetProvidersCountParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetProvidersCountParamsWithTimeout creates a new GetProvidersCountParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetProvidersCountParamsWithTimeout(timeout time.Duration) *GetProvidersCountParams {
	var ()
	return &GetProvidersCountParams{

		timeout: timeout,
	}
}

// NewGetProvidersCountParamsWithContext creates a new GetProvidersCountParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetProvidersCountParamsWithContext(ctx context.Context) *GetProvidersCountParams {
	var ()
	return &GetProvidersCountParams{

		Context: ctx,
	}
}

// NewGetProvidersCountParamsWithHTTPClient creates a new GetProvidersCountParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetProvidersCountParamsWithHTTPClient(client *http.Client) *GetProvidersCountParams {
	var ()
	return &GetProvidersCountParams{
		HTTPClient: client,
	}
}

/*GetProvidersCountParams contains all the parameters to send to the API endpoint
for the get providers count operation typically these are written to a http.Request
*/
type GetProvidersCountParams struct {

	/*Capability
	  CHALLENGE_DEPOSIT_VERIFICATION

	*/
	Capability *string
	/*DatasetDollarFilter
	  Expression to filter the providers by dataset(s) or dataset attribute(s). The default value will be the dataset or dataset attributes configured as default for the customer.

	*/
	DatasetDollarFilter *string
	/*Name
	  Name in minimum 1 character or routing number.

	*/
	Name *string
	/*Priority
	  Search priority

	*/
	Priority *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get providers count params
func (o *GetProvidersCountParams) WithTimeout(timeout time.Duration) *GetProvidersCountParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get providers count params
func (o *GetProvidersCountParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get providers count params
func (o *GetProvidersCountParams) WithContext(ctx context.Context) *GetProvidersCountParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get providers count params
func (o *GetProvidersCountParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get providers count params
func (o *GetProvidersCountParams) WithHTTPClient(client *http.Client) *GetProvidersCountParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get providers count params
func (o *GetProvidersCountParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCapability adds the capability to the get providers count params
func (o *GetProvidersCountParams) WithCapability(capability *string) *GetProvidersCountParams {
	o.SetCapability(capability)
	return o
}

// SetCapability adds the capability to the get providers count params
func (o *GetProvidersCountParams) SetCapability(capability *string) {
	o.Capability = capability
}

// WithDatasetDollarFilter adds the datasetDollarFilter to the get providers count params
func (o *GetProvidersCountParams) WithDatasetDollarFilter(datasetDollarFilter *string) *GetProvidersCountParams {
	o.SetDatasetDollarFilter(datasetDollarFilter)
	return o
}

// SetDatasetDollarFilter adds the datasetDollar Filter to the get providers count params
func (o *GetProvidersCountParams) SetDatasetDollarFilter(datasetDollarFilter *string) {
	o.DatasetDollarFilter = datasetDollarFilter
}

// WithName adds the name to the get providers count params
func (o *GetProvidersCountParams) WithName(name *string) *GetProvidersCountParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get providers count params
func (o *GetProvidersCountParams) SetName(name *string) {
	o.Name = name
}

// WithPriority adds the priority to the get providers count params
func (o *GetProvidersCountParams) WithPriority(priority *string) *GetProvidersCountParams {
	o.SetPriority(priority)
	return o
}

// SetPriority adds the priority to the get providers count params
func (o *GetProvidersCountParams) SetPriority(priority *string) {
	o.Priority = priority
}

// WriteToRequest writes these params to a swagger request
func (o *GetProvidersCountParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Capability != nil {

		// query param capability
		var qrCapability string
		if o.Capability != nil {
			qrCapability = *o.Capability
		}
		qCapability := qrCapability
		if qCapability != "" {
			if err := r.SetQueryParam("capability", qCapability); err != nil {
				return err
			}
		}

	}

	if o.DatasetDollarFilter != nil {

		// query param dataset$filter
		var qrDatasetDollarFilter string
		if o.DatasetDollarFilter != nil {
			qrDatasetDollarFilter = *o.DatasetDollarFilter
		}
		qDatasetDollarFilter := qrDatasetDollarFilter
		if qDatasetDollarFilter != "" {
			if err := r.SetQueryParam("dataset$filter", qDatasetDollarFilter); err != nil {
				return err
			}
		}

	}

	if o.Name != nil {

		// query param name
		var qrName string
		if o.Name != nil {
			qrName = *o.Name
		}
		qName := qrName
		if qName != "" {
			if err := r.SetQueryParam("name", qName); err != nil {
				return err
			}
		}

	}

	if o.Priority != nil {

		// query param priority
		var qrPriority string
		if o.Priority != nil {
			qrPriority = *o.Priority
		}
		qPriority := qrPriority
		if qPriority != "" {
			if err := r.SetQueryParam("priority", qPriority); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
