// Code generated by go-swagger; DO NOT EDIT.

package holdings

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/propertechnologies/yodlee-go/models"
)

// GetHoldingTypeListReader is a Reader for the GetHoldingTypeList structure.
type GetHoldingTypeListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetHoldingTypeListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetHoldingTypeListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetHoldingTypeListUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetHoldingTypeListNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetHoldingTypeListOK creates a GetHoldingTypeListOK with default headers values
func NewGetHoldingTypeListOK() *GetHoldingTypeListOK {
	return &GetHoldingTypeListOK{}
}

/*GetHoldingTypeListOK handles this case with default header values.

OK
*/
type GetHoldingTypeListOK struct {
	Payload *models.HoldingTypeListResponse
}

func (o *GetHoldingTypeListOK) Error() string {
	return fmt.Sprintf("[GET /holdings/holdingTypeList][%d] getHoldingTypeListOK  %+v", 200, o.Payload)
}

func (o *GetHoldingTypeListOK) GetPayload() *models.HoldingTypeListResponse {
	return o.Payload
}

func (o *GetHoldingTypeListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HoldingTypeListResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetHoldingTypeListUnauthorized creates a GetHoldingTypeListUnauthorized with default headers values
func NewGetHoldingTypeListUnauthorized() *GetHoldingTypeListUnauthorized {
	return &GetHoldingTypeListUnauthorized{}
}

/*GetHoldingTypeListUnauthorized handles this case with default header values.

Unauthorized
*/
type GetHoldingTypeListUnauthorized struct {
}

func (o *GetHoldingTypeListUnauthorized) Error() string {
	return fmt.Sprintf("[GET /holdings/holdingTypeList][%d] getHoldingTypeListUnauthorized ", 401)
}

func (o *GetHoldingTypeListUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetHoldingTypeListNotFound creates a GetHoldingTypeListNotFound with default headers values
func NewGetHoldingTypeListNotFound() *GetHoldingTypeListNotFound {
	return &GetHoldingTypeListNotFound{}
}

/*GetHoldingTypeListNotFound handles this case with default header values.

Not Found
*/
type GetHoldingTypeListNotFound struct {
}

func (o *GetHoldingTypeListNotFound) Error() string {
	return fmt.Sprintf("[GET /holdings/holdingTypeList][%d] getHoldingTypeListNotFound ", 404)
}

func (o *GetHoldingTypeListNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
