// Code generated by go-swagger; DO NOT EDIT.

package transactions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "yodlee-golang-client/models"
)

// DeleteTransactionCategoryReader is a Reader for the DeleteTransactionCategory structure.
type DeleteTransactionCategoryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteTransactionCategoryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteTransactionCategoryNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteTransactionCategoryBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewDeleteTransactionCategoryUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteTransactionCategoryNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteTransactionCategoryNoContent creates a DeleteTransactionCategoryNoContent with default headers values
func NewDeleteTransactionCategoryNoContent() *DeleteTransactionCategoryNoContent {
	return &DeleteTransactionCategoryNoContent{}
}

/*DeleteTransactionCategoryNoContent handles this case with default header values.

Deleted Successfully
*/
type DeleteTransactionCategoryNoContent struct {
}

func (o *DeleteTransactionCategoryNoContent) Error() string {
	return fmt.Sprintf("[DELETE /transactions/categories/{categoryId}][%d] deleteTransactionCategoryNoContent ", 204)
}

func (o *DeleteTransactionCategoryNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteTransactionCategoryBadRequest creates a DeleteTransactionCategoryBadRequest with default headers values
func NewDeleteTransactionCategoryBadRequest() *DeleteTransactionCategoryBadRequest {
	return &DeleteTransactionCategoryBadRequest{}
}

/*DeleteTransactionCategoryBadRequest handles this case with default header values.

Y800 : Invalid value for categoryId
*/
type DeleteTransactionCategoryBadRequest struct {
	Payload *models.YodleeError
}

func (o *DeleteTransactionCategoryBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /transactions/categories/{categoryId}][%d] deleteTransactionCategoryBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteTransactionCategoryBadRequest) GetPayload() *models.YodleeError {
	return o.Payload
}

func (o *DeleteTransactionCategoryBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.YodleeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteTransactionCategoryUnauthorized creates a DeleteTransactionCategoryUnauthorized with default headers values
func NewDeleteTransactionCategoryUnauthorized() *DeleteTransactionCategoryUnauthorized {
	return &DeleteTransactionCategoryUnauthorized{}
}

/*DeleteTransactionCategoryUnauthorized handles this case with default header values.

Unauthorized
*/
type DeleteTransactionCategoryUnauthorized struct {
}

func (o *DeleteTransactionCategoryUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /transactions/categories/{categoryId}][%d] deleteTransactionCategoryUnauthorized ", 401)
}

func (o *DeleteTransactionCategoryUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteTransactionCategoryNotFound creates a DeleteTransactionCategoryNotFound with default headers values
func NewDeleteTransactionCategoryNotFound() *DeleteTransactionCategoryNotFound {
	return &DeleteTransactionCategoryNotFound{}
}

/*DeleteTransactionCategoryNotFound handles this case with default header values.

Not Found
*/
type DeleteTransactionCategoryNotFound struct {
}

func (o *DeleteTransactionCategoryNotFound) Error() string {
	return fmt.Sprintf("[DELETE /transactions/categories/{categoryId}][%d] deleteTransactionCategoryNotFound ", 404)
}

func (o *DeleteTransactionCategoryNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
