// Code generated by go-swagger; DO NOT EDIT.

package transactions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetTransactionsParams creates a new GetTransactionsParams object
// with the default values initialized.
func NewGetTransactionsParams() *GetTransactionsParams {
	var ()
	return &GetTransactionsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetTransactionsParamsWithTimeout creates a new GetTransactionsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetTransactionsParamsWithTimeout(timeout time.Duration) *GetTransactionsParams {
	var ()
	return &GetTransactionsParams{

		timeout: timeout,
	}
}

// NewGetTransactionsParamsWithContext creates a new GetTransactionsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetTransactionsParamsWithContext(ctx context.Context) *GetTransactionsParams {
	var ()
	return &GetTransactionsParams{

		Context: ctx,
	}
}

// NewGetTransactionsParamsWithHTTPClient creates a new GetTransactionsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetTransactionsParamsWithHTTPClient(client *http.Client) *GetTransactionsParams {
	var ()
	return &GetTransactionsParams{
		HTTPClient: client,
	}
}

/*GetTransactionsParams contains all the parameters to send to the API endpoint
for the get transactions operation typically these are written to a http.Request
*/
type GetTransactionsParams struct {

	/*AccountID
	  Comma separated accountIds

	*/
	AccountID *string
	/*BaseType
	  DEBIT/CREDIT

	*/
	BaseType *string
	/*CategoryID
	  Comma separated categoryIds

	*/
	CategoryID *string
	/*CategoryType
	  Transaction Category Type(UNCATEGORIZE, INCOME, TRANSFER, EXPENSE or DEFERRED_COMPENSATION)

	*/
	CategoryType *string
	/*Container
	  bank/creditCard/investment/insurance/loan

	*/
	Container *string
	/*DetailCategoryID
	  Comma separated detailCategoryIds

	*/
	DetailCategoryID *string
	/*FromDate
	  Transaction from date(YYYY-MM-DD)

	*/
	FromDate *string
	/*HighLevelCategoryID
	  Comma separated highLevelCategoryIds

	*/
	HighLevelCategoryID *string
	/*Keyword
	  Transaction search text

	*/
	Keyword *string
	/*Skip
	  skip (Min 0)

	*/
	Skip *int32
	/*ToDate
	  Transaction end date (YYYY-MM-DD)

	*/
	ToDate *string
	/*Top
	  top (Max 500)

	*/
	Top *int32
	/*Type
	  Transaction Type(SELL,SWEEP, etc.) for bank/creditCard/investment

	*/
	Type *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get transactions params
func (o *GetTransactionsParams) WithTimeout(timeout time.Duration) *GetTransactionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get transactions params
func (o *GetTransactionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get transactions params
func (o *GetTransactionsParams) WithContext(ctx context.Context) *GetTransactionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get transactions params
func (o *GetTransactionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get transactions params
func (o *GetTransactionsParams) WithHTTPClient(client *http.Client) *GetTransactionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get transactions params
func (o *GetTransactionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccountID adds the accountID to the get transactions params
func (o *GetTransactionsParams) WithAccountID(accountID *string) *GetTransactionsParams {
	o.SetAccountID(accountID)
	return o
}

// SetAccountID adds the accountId to the get transactions params
func (o *GetTransactionsParams) SetAccountID(accountID *string) {
	o.AccountID = accountID
}

// WithBaseType adds the baseType to the get transactions params
func (o *GetTransactionsParams) WithBaseType(baseType *string) *GetTransactionsParams {
	o.SetBaseType(baseType)
	return o
}

// SetBaseType adds the baseType to the get transactions params
func (o *GetTransactionsParams) SetBaseType(baseType *string) {
	o.BaseType = baseType
}

// WithCategoryID adds the categoryID to the get transactions params
func (o *GetTransactionsParams) WithCategoryID(categoryID *string) *GetTransactionsParams {
	o.SetCategoryID(categoryID)
	return o
}

// SetCategoryID adds the categoryId to the get transactions params
func (o *GetTransactionsParams) SetCategoryID(categoryID *string) {
	o.CategoryID = categoryID
}

// WithCategoryType adds the categoryType to the get transactions params
func (o *GetTransactionsParams) WithCategoryType(categoryType *string) *GetTransactionsParams {
	o.SetCategoryType(categoryType)
	return o
}

// SetCategoryType adds the categoryType to the get transactions params
func (o *GetTransactionsParams) SetCategoryType(categoryType *string) {
	o.CategoryType = categoryType
}

// WithContainer adds the container to the get transactions params
func (o *GetTransactionsParams) WithContainer(container *string) *GetTransactionsParams {
	o.SetContainer(container)
	return o
}

// SetContainer adds the container to the get transactions params
func (o *GetTransactionsParams) SetContainer(container *string) {
	o.Container = container
}

// WithDetailCategoryID adds the detailCategoryID to the get transactions params
func (o *GetTransactionsParams) WithDetailCategoryID(detailCategoryID *string) *GetTransactionsParams {
	o.SetDetailCategoryID(detailCategoryID)
	return o
}

// SetDetailCategoryID adds the detailCategoryId to the get transactions params
func (o *GetTransactionsParams) SetDetailCategoryID(detailCategoryID *string) {
	o.DetailCategoryID = detailCategoryID
}

// WithFromDate adds the fromDate to the get transactions params
func (o *GetTransactionsParams) WithFromDate(fromDate *string) *GetTransactionsParams {
	o.SetFromDate(fromDate)
	return o
}

// SetFromDate adds the fromDate to the get transactions params
func (o *GetTransactionsParams) SetFromDate(fromDate *string) {
	o.FromDate = fromDate
}

// WithHighLevelCategoryID adds the highLevelCategoryID to the get transactions params
func (o *GetTransactionsParams) WithHighLevelCategoryID(highLevelCategoryID *string) *GetTransactionsParams {
	o.SetHighLevelCategoryID(highLevelCategoryID)
	return o
}

// SetHighLevelCategoryID adds the highLevelCategoryId to the get transactions params
func (o *GetTransactionsParams) SetHighLevelCategoryID(highLevelCategoryID *string) {
	o.HighLevelCategoryID = highLevelCategoryID
}

// WithKeyword adds the keyword to the get transactions params
func (o *GetTransactionsParams) WithKeyword(keyword *string) *GetTransactionsParams {
	o.SetKeyword(keyword)
	return o
}

// SetKeyword adds the keyword to the get transactions params
func (o *GetTransactionsParams) SetKeyword(keyword *string) {
	o.Keyword = keyword
}

// WithSkip adds the skip to the get transactions params
func (o *GetTransactionsParams) WithSkip(skip *int32) *GetTransactionsParams {
	o.SetSkip(skip)
	return o
}

// SetSkip adds the skip to the get transactions params
func (o *GetTransactionsParams) SetSkip(skip *int32) {
	o.Skip = skip
}

// WithToDate adds the toDate to the get transactions params
func (o *GetTransactionsParams) WithToDate(toDate *string) *GetTransactionsParams {
	o.SetToDate(toDate)
	return o
}

// SetToDate adds the toDate to the get transactions params
func (o *GetTransactionsParams) SetToDate(toDate *string) {
	o.ToDate = toDate
}

// WithTop adds the top to the get transactions params
func (o *GetTransactionsParams) WithTop(top *int32) *GetTransactionsParams {
	o.SetTop(top)
	return o
}

// SetTop adds the top to the get transactions params
func (o *GetTransactionsParams) SetTop(top *int32) {
	o.Top = top
}

// WithType adds the typeVar to the get transactions params
func (o *GetTransactionsParams) WithType(typeVar *string) *GetTransactionsParams {
	o.SetType(typeVar)
	return o
}

// SetType adds the type to the get transactions params
func (o *GetTransactionsParams) SetType(typeVar *string) {
	o.Type = typeVar
}

// WriteToRequest writes these params to a swagger request
func (o *GetTransactionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.AccountID != nil {

		// query param accountId
		var qrAccountID string
		if o.AccountID != nil {
			qrAccountID = *o.AccountID
		}
		qAccountID := qrAccountID
		if qAccountID != "" {
			if err := r.SetQueryParam("accountId", qAccountID); err != nil {
				return err
			}
		}

	}

	if o.BaseType != nil {

		// query param baseType
		var qrBaseType string
		if o.BaseType != nil {
			qrBaseType = *o.BaseType
		}
		qBaseType := qrBaseType
		if qBaseType != "" {
			if err := r.SetQueryParam("baseType", qBaseType); err != nil {
				return err
			}
		}

	}

	if o.CategoryID != nil {

		// query param categoryId
		var qrCategoryID string
		if o.CategoryID != nil {
			qrCategoryID = *o.CategoryID
		}
		qCategoryID := qrCategoryID
		if qCategoryID != "" {
			if err := r.SetQueryParam("categoryId", qCategoryID); err != nil {
				return err
			}
		}

	}

	if o.CategoryType != nil {

		// query param categoryType
		var qrCategoryType string
		if o.CategoryType != nil {
			qrCategoryType = *o.CategoryType
		}
		qCategoryType := qrCategoryType
		if qCategoryType != "" {
			if err := r.SetQueryParam("categoryType", qCategoryType); err != nil {
				return err
			}
		}

	}

	if o.Container != nil {

		// query param container
		var qrContainer string
		if o.Container != nil {
			qrContainer = *o.Container
		}
		qContainer := qrContainer
		if qContainer != "" {
			if err := r.SetQueryParam("container", qContainer); err != nil {
				return err
			}
		}

	}

	if o.DetailCategoryID != nil {

		// query param detailCategoryId
		var qrDetailCategoryID string
		if o.DetailCategoryID != nil {
			qrDetailCategoryID = *o.DetailCategoryID
		}
		qDetailCategoryID := qrDetailCategoryID
		if qDetailCategoryID != "" {
			if err := r.SetQueryParam("detailCategoryId", qDetailCategoryID); err != nil {
				return err
			}
		}

	}

	if o.FromDate != nil {

		// query param fromDate
		var qrFromDate string
		if o.FromDate != nil {
			qrFromDate = *o.FromDate
		}
		qFromDate := qrFromDate
		if qFromDate != "" {
			if err := r.SetQueryParam("fromDate", qFromDate); err != nil {
				return err
			}
		}

	}

	if o.HighLevelCategoryID != nil {

		// query param highLevelCategoryId
		var qrHighLevelCategoryID string
		if o.HighLevelCategoryID != nil {
			qrHighLevelCategoryID = *o.HighLevelCategoryID
		}
		qHighLevelCategoryID := qrHighLevelCategoryID
		if qHighLevelCategoryID != "" {
			if err := r.SetQueryParam("highLevelCategoryId", qHighLevelCategoryID); err != nil {
				return err
			}
		}

	}

	if o.Keyword != nil {

		// query param keyword
		var qrKeyword string
		if o.Keyword != nil {
			qrKeyword = *o.Keyword
		}
		qKeyword := qrKeyword
		if qKeyword != "" {
			if err := r.SetQueryParam("keyword", qKeyword); err != nil {
				return err
			}
		}

	}

	if o.Skip != nil {

		// query param skip
		var qrSkip int32
		if o.Skip != nil {
			qrSkip = *o.Skip
		}
		qSkip := swag.FormatInt32(qrSkip)
		if qSkip != "" {
			if err := r.SetQueryParam("skip", qSkip); err != nil {
				return err
			}
		}

	}

	if o.ToDate != nil {

		// query param toDate
		var qrToDate string
		if o.ToDate != nil {
			qrToDate = *o.ToDate
		}
		qToDate := qrToDate
		if qToDate != "" {
			if err := r.SetQueryParam("toDate", qToDate); err != nil {
				return err
			}
		}

	}

	if o.Top != nil {

		// query param top
		var qrTop int32
		if o.Top != nil {
			qrTop = *o.Top
		}
		qTop := swag.FormatInt32(qrTop)
		if qTop != "" {
			if err := r.SetQueryParam("top", qTop); err != nil {
				return err
			}
		}

	}

	if o.Type != nil {

		// query param type
		var qrType string
		if o.Type != nil {
			qrType = *o.Type
		}
		qType := qrType
		if qType != "" {
			if err := r.SetQueryParam("type", qType); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
