// Code generated by go-swagger; DO NOT EDIT.

package transactions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetTransactionCategoriesParams creates a new GetTransactionCategoriesParams object
// with the default values initialized.
func NewGetTransactionCategoriesParams() *GetTransactionCategoriesParams {

	return &GetTransactionCategoriesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetTransactionCategoriesParamsWithTimeout creates a new GetTransactionCategoriesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetTransactionCategoriesParamsWithTimeout(timeout time.Duration) *GetTransactionCategoriesParams {

	return &GetTransactionCategoriesParams{

		timeout: timeout,
	}
}

// NewGetTransactionCategoriesParamsWithContext creates a new GetTransactionCategoriesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetTransactionCategoriesParamsWithContext(ctx context.Context) *GetTransactionCategoriesParams {

	return &GetTransactionCategoriesParams{

		Context: ctx,
	}
}

// NewGetTransactionCategoriesParamsWithHTTPClient creates a new GetTransactionCategoriesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetTransactionCategoriesParamsWithHTTPClient(client *http.Client) *GetTransactionCategoriesParams {

	return &GetTransactionCategoriesParams{
		HTTPClient: client,
	}
}

/*GetTransactionCategoriesParams contains all the parameters to send to the API endpoint
for the get transaction categories operation typically these are written to a http.Request
*/
type GetTransactionCategoriesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get transaction categories params
func (o *GetTransactionCategoriesParams) WithTimeout(timeout time.Duration) *GetTransactionCategoriesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get transaction categories params
func (o *GetTransactionCategoriesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get transaction categories params
func (o *GetTransactionCategoriesParams) WithContext(ctx context.Context) *GetTransactionCategoriesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get transaction categories params
func (o *GetTransactionCategoriesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get transaction categories params
func (o *GetTransactionCategoriesParams) WithHTTPClient(client *http.Client) *GetTransactionCategoriesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get transaction categories params
func (o *GetTransactionCategoriesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetTransactionCategoriesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
