// Code generated by go-swagger; DO NOT EDIT.

package transactions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "yodlee-golang-client/models"
)

// NewUpdateTransactionCategorizationRuleParams creates a new UpdateTransactionCategorizationRuleParams object
// with the default values initialized.
func NewUpdateTransactionCategorizationRuleParams() *UpdateTransactionCategorizationRuleParams {
	var ()
	return &UpdateTransactionCategorizationRuleParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateTransactionCategorizationRuleParamsWithTimeout creates a new UpdateTransactionCategorizationRuleParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateTransactionCategorizationRuleParamsWithTimeout(timeout time.Duration) *UpdateTransactionCategorizationRuleParams {
	var ()
	return &UpdateTransactionCategorizationRuleParams{

		timeout: timeout,
	}
}

// NewUpdateTransactionCategorizationRuleParamsWithContext creates a new UpdateTransactionCategorizationRuleParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateTransactionCategorizationRuleParamsWithContext(ctx context.Context) *UpdateTransactionCategorizationRuleParams {
	var ()
	return &UpdateTransactionCategorizationRuleParams{

		Context: ctx,
	}
}

// NewUpdateTransactionCategorizationRuleParamsWithHTTPClient creates a new UpdateTransactionCategorizationRuleParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateTransactionCategorizationRuleParamsWithHTTPClient(client *http.Client) *UpdateTransactionCategorizationRuleParams {
	var ()
	return &UpdateTransactionCategorizationRuleParams{
		HTTPClient: client,
	}
}

/*UpdateTransactionCategorizationRuleParams contains all the parameters to send to the API endpoint
for the update transaction categorization rule operation typically these are written to a http.Request
*/
type UpdateTransactionCategorizationRuleParams struct {

	/*RuleID
	  ruleId

	*/
	RuleID int64
	/*TransactionCategoriesRuleRequest
	  transactionCategoriesRuleRequest

	*/
	TransactionCategoriesRuleRequest *models.TransactionCategorizationRuleRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update transaction categorization rule params
func (o *UpdateTransactionCategorizationRuleParams) WithTimeout(timeout time.Duration) *UpdateTransactionCategorizationRuleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update transaction categorization rule params
func (o *UpdateTransactionCategorizationRuleParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update transaction categorization rule params
func (o *UpdateTransactionCategorizationRuleParams) WithContext(ctx context.Context) *UpdateTransactionCategorizationRuleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update transaction categorization rule params
func (o *UpdateTransactionCategorizationRuleParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update transaction categorization rule params
func (o *UpdateTransactionCategorizationRuleParams) WithHTTPClient(client *http.Client) *UpdateTransactionCategorizationRuleParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update transaction categorization rule params
func (o *UpdateTransactionCategorizationRuleParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRuleID adds the ruleID to the update transaction categorization rule params
func (o *UpdateTransactionCategorizationRuleParams) WithRuleID(ruleID int64) *UpdateTransactionCategorizationRuleParams {
	o.SetRuleID(ruleID)
	return o
}

// SetRuleID adds the ruleId to the update transaction categorization rule params
func (o *UpdateTransactionCategorizationRuleParams) SetRuleID(ruleID int64) {
	o.RuleID = ruleID
}

// WithTransactionCategoriesRuleRequest adds the transactionCategoriesRuleRequest to the update transaction categorization rule params
func (o *UpdateTransactionCategorizationRuleParams) WithTransactionCategoriesRuleRequest(transactionCategoriesRuleRequest *models.TransactionCategorizationRuleRequest) *UpdateTransactionCategorizationRuleParams {
	o.SetTransactionCategoriesRuleRequest(transactionCategoriesRuleRequest)
	return o
}

// SetTransactionCategoriesRuleRequest adds the transactionCategoriesRuleRequest to the update transaction categorization rule params
func (o *UpdateTransactionCategorizationRuleParams) SetTransactionCategoriesRuleRequest(transactionCategoriesRuleRequest *models.TransactionCategorizationRuleRequest) {
	o.TransactionCategoriesRuleRequest = transactionCategoriesRuleRequest
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateTransactionCategorizationRuleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param ruleId
	if err := r.SetPathParam("ruleId", swag.FormatInt64(o.RuleID)); err != nil {
		return err
	}

	if o.TransactionCategoriesRuleRequest != nil {
		if err := r.SetBodyParam(o.TransactionCategoriesRuleRequest); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
