// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/propertechnologies/yodlee-go/models"
)

// DeleteAPIKeyReader is a Reader for the DeleteAPIKey structure.
type DeleteAPIKeyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAPIKeyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewDeleteAPIKeyCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 204:
		result := NewDeleteAPIKeyNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteAPIKeyBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewDeleteAPIKeyUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteAPIKeyNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteAPIKeyCreated creates a DeleteAPIKeyCreated with default headers values
func NewDeleteAPIKeyCreated() *DeleteAPIKeyCreated {
	return &DeleteAPIKeyCreated{}
}

/*DeleteAPIKeyCreated handles this case with default header values.

OK
*/
type DeleteAPIKeyCreated struct {
}

func (o *DeleteAPIKeyCreated) Error() string {
	return fmt.Sprintf("[DELETE /auth/apiKey/{key}][%d] deleteApiKeyCreated ", 201)
}

func (o *DeleteAPIKeyCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteAPIKeyNoContent creates a DeleteAPIKeyNoContent with default headers values
func NewDeleteAPIKeyNoContent() *DeleteAPIKeyNoContent {
	return &DeleteAPIKeyNoContent{}
}

/*DeleteAPIKeyNoContent handles this case with default header values.

No Content
*/
type DeleteAPIKeyNoContent struct {
}

func (o *DeleteAPIKeyNoContent) Error() string {
	return fmt.Sprintf("[DELETE /auth/apiKey/{key}][%d] deleteApiKeyNoContent ", 204)
}

func (o *DeleteAPIKeyNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteAPIKeyBadRequest creates a DeleteAPIKeyBadRequest with default headers values
func NewDeleteAPIKeyBadRequest() *DeleteAPIKeyBadRequest {
	return &DeleteAPIKeyBadRequest{}
}

/*DeleteAPIKeyBadRequest handles this case with default header values.

Y807 : Resource not found<br>Y806 : Invalid input
*/
type DeleteAPIKeyBadRequest struct {
	Payload *models.YodleeError
}

func (o *DeleteAPIKeyBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /auth/apiKey/{key}][%d] deleteApiKeyBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteAPIKeyBadRequest) GetPayload() *models.YodleeError {
	return o.Payload
}

func (o *DeleteAPIKeyBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.YodleeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteAPIKeyUnauthorized creates a DeleteAPIKeyUnauthorized with default headers values
func NewDeleteAPIKeyUnauthorized() *DeleteAPIKeyUnauthorized {
	return &DeleteAPIKeyUnauthorized{}
}

/*DeleteAPIKeyUnauthorized handles this case with default header values.

Unauthorized
*/
type DeleteAPIKeyUnauthorized struct {
}

func (o *DeleteAPIKeyUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /auth/apiKey/{key}][%d] deleteApiKeyUnauthorized ", 401)
}

func (o *DeleteAPIKeyUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteAPIKeyNotFound creates a DeleteAPIKeyNotFound with default headers values
func NewDeleteAPIKeyNotFound() *DeleteAPIKeyNotFound {
	return &DeleteAPIKeyNotFound{}
}

/*DeleteAPIKeyNotFound handles this case with default header values.

Not Found
*/
type DeleteAPIKeyNotFound struct {
}

func (o *DeleteAPIKeyNotFound) Error() string {
	return fmt.Sprintf("[DELETE /auth/apiKey/{key}][%d] deleteApiKeyNotFound ", 404)
}

func (o *DeleteAPIKeyNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
