// Code generated by go-swagger; DO NOT EDIT.

package data_extracts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetDataExtractsUserDataParams creates a new GetDataExtractsUserDataParams object
// with the default values initialized.
func NewGetDataExtractsUserDataParams() *GetDataExtractsUserDataParams {
	var ()
	return &GetDataExtractsUserDataParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetDataExtractsUserDataParamsWithTimeout creates a new GetDataExtractsUserDataParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetDataExtractsUserDataParamsWithTimeout(timeout time.Duration) *GetDataExtractsUserDataParams {
	var ()
	return &GetDataExtractsUserDataParams{

		timeout: timeout,
	}
}

// NewGetDataExtractsUserDataParamsWithContext creates a new GetDataExtractsUserDataParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetDataExtractsUserDataParamsWithContext(ctx context.Context) *GetDataExtractsUserDataParams {
	var ()
	return &GetDataExtractsUserDataParams{

		Context: ctx,
	}
}

// NewGetDataExtractsUserDataParamsWithHTTPClient creates a new GetDataExtractsUserDataParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetDataExtractsUserDataParamsWithHTTPClient(client *http.Client) *GetDataExtractsUserDataParams {
	var ()
	return &GetDataExtractsUserDataParams{
		HTTPClient: client,
	}
}

/*GetDataExtractsUserDataParams contains all the parameters to send to the API endpoint
for the get data extracts user data operation typically these are written to a http.Request
*/
type GetDataExtractsUserDataParams struct {

	/*FromDate
	  From DateTime (YYYY-MM-DDThh:mm:ssZ)

	*/
	FromDate string
	/*LoginName
	  Login Name

	*/
	LoginName string
	/*ToDate
	  To DateTime (YYYY-MM-DDThh:mm:ssZ)

	*/
	ToDate string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get data extracts user data params
func (o *GetDataExtractsUserDataParams) WithTimeout(timeout time.Duration) *GetDataExtractsUserDataParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get data extracts user data params
func (o *GetDataExtractsUserDataParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get data extracts user data params
func (o *GetDataExtractsUserDataParams) WithContext(ctx context.Context) *GetDataExtractsUserDataParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get data extracts user data params
func (o *GetDataExtractsUserDataParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get data extracts user data params
func (o *GetDataExtractsUserDataParams) WithHTTPClient(client *http.Client) *GetDataExtractsUserDataParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get data extracts user data params
func (o *GetDataExtractsUserDataParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFromDate adds the fromDate to the get data extracts user data params
func (o *GetDataExtractsUserDataParams) WithFromDate(fromDate string) *GetDataExtractsUserDataParams {
	o.SetFromDate(fromDate)
	return o
}

// SetFromDate adds the fromDate to the get data extracts user data params
func (o *GetDataExtractsUserDataParams) SetFromDate(fromDate string) {
	o.FromDate = fromDate
}

// WithLoginName adds the loginName to the get data extracts user data params
func (o *GetDataExtractsUserDataParams) WithLoginName(loginName string) *GetDataExtractsUserDataParams {
	o.SetLoginName(loginName)
	return o
}

// SetLoginName adds the loginName to the get data extracts user data params
func (o *GetDataExtractsUserDataParams) SetLoginName(loginName string) {
	o.LoginName = loginName
}

// WithToDate adds the toDate to the get data extracts user data params
func (o *GetDataExtractsUserDataParams) WithToDate(toDate string) *GetDataExtractsUserDataParams {
	o.SetToDate(toDate)
	return o
}

// SetToDate adds the toDate to the get data extracts user data params
func (o *GetDataExtractsUserDataParams) SetToDate(toDate string) {
	o.ToDate = toDate
}

// WriteToRequest writes these params to a swagger request
func (o *GetDataExtractsUserDataParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param fromDate
	qrFromDate := o.FromDate
	qFromDate := qrFromDate
	if qFromDate != "" {
		if err := r.SetQueryParam("fromDate", qFromDate); err != nil {
			return err
		}
	}

	// query param loginName
	qrLoginName := o.LoginName
	qLoginName := qrLoginName
	if qLoginName != "" {
		if err := r.SetQueryParam("loginName", qLoginName); err != nil {
			return err
		}
	}

	// query param toDate
	qrToDate := o.ToDate
	qToDate := qrToDate
	if qToDate != "" {
		if err := r.SetQueryParam("toDate", qToDate); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
