// Code generated by go-swagger; DO NOT EDIT.

package accounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "yodlee-golang-client/models"
)

// CreateManualAccountReader is a Reader for the CreateManualAccount structure.
type CreateManualAccountReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateManualAccountReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateManualAccountOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateManualAccountBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewCreateManualAccountUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewCreateManualAccountNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateManualAccountOK creates a CreateManualAccountOK with default headers values
func NewCreateManualAccountOK() *CreateManualAccountOK {
	return &CreateManualAccountOK{}
}

/*CreateManualAccountOK handles this case with default header values.

OK
*/
type CreateManualAccountOK struct {
	Payload *models.CreatedAccountResponse
}

func (o *CreateManualAccountOK) Error() string {
	return fmt.Sprintf("[POST /accounts][%d] createManualAccountOK  %+v", 200, o.Payload)
}

func (o *CreateManualAccountOK) GetPayload() *models.CreatedAccountResponse {
	return o.Payload
}

func (o *CreateManualAccountOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CreatedAccountResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateManualAccountBadRequest creates a CreateManualAccountBadRequest with default headers values
func NewCreateManualAccountBadRequest() *CreateManualAccountBadRequest {
	return &CreateManualAccountBadRequest{}
}

/*CreateManualAccountBadRequest handles this case with default header values.

Y800 : Invalid value for accountParam
*/
type CreateManualAccountBadRequest struct {
	Payload *models.YodleeError
}

func (o *CreateManualAccountBadRequest) Error() string {
	return fmt.Sprintf("[POST /accounts][%d] createManualAccountBadRequest  %+v", 400, o.Payload)
}

func (o *CreateManualAccountBadRequest) GetPayload() *models.YodleeError {
	return o.Payload
}

func (o *CreateManualAccountBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.YodleeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateManualAccountUnauthorized creates a CreateManualAccountUnauthorized with default headers values
func NewCreateManualAccountUnauthorized() *CreateManualAccountUnauthorized {
	return &CreateManualAccountUnauthorized{}
}

/*CreateManualAccountUnauthorized handles this case with default header values.

Unauthorized
*/
type CreateManualAccountUnauthorized struct {
}

func (o *CreateManualAccountUnauthorized) Error() string {
	return fmt.Sprintf("[POST /accounts][%d] createManualAccountUnauthorized ", 401)
}

func (o *CreateManualAccountUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateManualAccountNotFound creates a CreateManualAccountNotFound with default headers values
func NewCreateManualAccountNotFound() *CreateManualAccountNotFound {
	return &CreateManualAccountNotFound{}
}

/*CreateManualAccountNotFound handles this case with default header values.

Not Found
*/
type CreateManualAccountNotFound struct {
}

func (o *CreateManualAccountNotFound) Error() string {
	return fmt.Sprintf("[POST /accounts][%d] createManualAccountNotFound ", 404)
}

func (o *CreateManualAccountNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
