// Code generated by go-swagger; DO NOT EDIT.

package accounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAccountParams creates a new GetAccountParams object
// with the default values initialized.
func NewGetAccountParams() *GetAccountParams {
	var ()
	return &GetAccountParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAccountParamsWithTimeout creates a new GetAccountParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAccountParamsWithTimeout(timeout time.Duration) *GetAccountParams {
	var ()
	return &GetAccountParams{

		timeout: timeout,
	}
}

// NewGetAccountParamsWithContext creates a new GetAccountParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAccountParamsWithContext(ctx context.Context) *GetAccountParams {
	var ()
	return &GetAccountParams{

		Context: ctx,
	}
}

// NewGetAccountParamsWithHTTPClient creates a new GetAccountParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAccountParamsWithHTTPClient(client *http.Client) *GetAccountParams {
	var ()
	return &GetAccountParams{
		HTTPClient: client,
	}
}

/*GetAccountParams contains all the parameters to send to the API endpoint
for the get account operation typically these are written to a http.Request
*/
type GetAccountParams struct {

	/*AccountID
	  accountId

	*/
	AccountID int64
	/*Container
	  bank/creditCard/investment/insurance/loan/reward/bill/realEstate/otherAssets/otherLiabilities
	* bank: Applicable for Aggregated and Manual<br>
	* creditCard: Applicable for Aggregated and Manual<br>
	* investment: Applicable for Aggregated and Manual<br>
	* insurance: Applicable for Aggregated and Manual<br>
	* loan: Applicable for Aggregated and Manual<br>
	* reward: Applicable for Aggregated and Manual<br>
	* bill: Applicable for Aggregated and Manual<br>
	* realEstate: Applicable for Manual<br>
	* otherAssets: Applicable for Manual<br>
	* otherLiabilities: Applicable for Manual

	*/
	Container string
	/*Include
	  profile, holder, fullAccountNumber, paymentProfile, autoRefresh

	*/
	Include *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get account params
func (o *GetAccountParams) WithTimeout(timeout time.Duration) *GetAccountParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get account params
func (o *GetAccountParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get account params
func (o *GetAccountParams) WithContext(ctx context.Context) *GetAccountParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get account params
func (o *GetAccountParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get account params
func (o *GetAccountParams) WithHTTPClient(client *http.Client) *GetAccountParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get account params
func (o *GetAccountParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccountID adds the accountID to the get account params
func (o *GetAccountParams) WithAccountID(accountID int64) *GetAccountParams {
	o.SetAccountID(accountID)
	return o
}

// SetAccountID adds the accountId to the get account params
func (o *GetAccountParams) SetAccountID(accountID int64) {
	o.AccountID = accountID
}

// WithContainer adds the container to the get account params
func (o *GetAccountParams) WithContainer(container string) *GetAccountParams {
	o.SetContainer(container)
	return o
}

// SetContainer adds the container to the get account params
func (o *GetAccountParams) SetContainer(container string) {
	o.Container = container
}

// WithInclude adds the include to the get account params
func (o *GetAccountParams) WithInclude(include *string) *GetAccountParams {
	o.SetInclude(include)
	return o
}

// SetInclude adds the include to the get account params
func (o *GetAccountParams) SetInclude(include *string) {
	o.Include = include
}

// WriteToRequest writes these params to a swagger request
func (o *GetAccountParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param accountId
	if err := r.SetPathParam("accountId", swag.FormatInt64(o.AccountID)); err != nil {
		return err
	}

	// query param container
	qrContainer := o.Container
	qContainer := qrContainer
	if qContainer != "" {
		if err := r.SetQueryParam("container", qContainer); err != nil {
			return err
		}
	}

	if o.Include != nil {

		// query param include
		var qrInclude string
		if o.Include != nil {
			qrInclude = *o.Include
		}
		qInclude := qrInclude
		if qInclude != "" {
			if err := r.SetQueryParam("include", qInclude); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
