// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// DataExtractsEventLinks DataExtractsEventLinks
// swagger:model DataExtractsEventLinks
type DataExtractsEventLinks struct {

	// href
	// Read Only: true
	Href string `json:"href,omitempty"`

	// method type
	// Read Only: true
	MethodType string `json:"methodType,omitempty"`

	// rel
	// Read Only: true
	Rel string `json:"rel,omitempty"`
}

// Validate validates this data extracts event links
func (m *DataExtractsEventLinks) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DataExtractsEventLinks) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DataExtractsEventLinks) UnmarshalBinary(b []byte) error {
	var res DataExtractsEventLinks
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
