// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// DataExtractsUserDataResponse DataExtractsUserDataResponse
// swagger:model DataExtractsUserDataResponse
type DataExtractsUserDataResponse struct {

	// user data
	// Read Only: true
	UserData []*DataExtractsUserData `json:"userData"`
}

// Validate validates this data extracts user data response
func (m *DataExtractsUserDataResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateUserData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DataExtractsUserDataResponse) validateUserData(formats strfmt.Registry) error {

	if swag.IsZero(m.UserData) { // not required
		return nil
	}

	for i := 0; i < len(m.UserData); i++ {
		if swag.IsZero(m.UserData[i]) { // not required
			continue
		}

		if m.UserData[i] != nil {
			if err := m.UserData[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("userData" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *DataExtractsUserDataResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DataExtractsUserDataResponse) UnmarshalBinary(b []byte) error {
	var res DataExtractsUserDataResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
