// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// DataExtractsUser DataExtractsUser
// swagger:model DataExtractsUser
type DataExtractsUser struct {

	// login name
	// Read Only: true
	LoginName string `json:"loginName,omitempty"`
}

// Validate validates this data extracts user
func (m *DataExtractsUser) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DataExtractsUser) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DataExtractsUser) UnmarshalBinary(b []byte) error {
	var res DataExtractsUser
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
