// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// DerivedNetworthResponse DerivedNetworthResponse
// swagger:model DerivedNetworthResponse
type DerivedNetworthResponse struct {

	// networth
	// Read Only: true
	Networth []*DerivedNetworth `json:"networth"`
}

// Validate validates this derived networth response
func (m *DerivedNetworthResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateNetworth(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DerivedNetworthResponse) validateNetworth(formats strfmt.Registry) error {

	if swag.IsZero(m.Networth) { // not required
		return nil
	}

	for i := 0; i < len(m.Networth); i++ {
		if swag.IsZero(m.Networth[i]) { // not required
			continue
		}

		if m.Networth[i] != nil {
			if err := m.Networth[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("networth" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *DerivedNetworthResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DerivedNetworthResponse) UnmarshalBinary(b []byte) error {
	var res DerivedNetworthResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
