// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// DerivedHoldingSummaryResponse DerivedHoldingSummaryResponse
// swagger:model DerivedHoldingSummaryResponse
type DerivedHoldingSummaryResponse struct {

	// holding summary
	// Read Only: true
	HoldingSummary []*DerivedHoldingsSummary `json:"holdingSummary"`

	// link
	// Read Only: true
	Link *DerivedHoldingsLinks `json:"link,omitempty"`
}

// Validate validates this derived holding summary response
func (m *DerivedHoldingSummaryResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateHoldingSummary(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLink(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DerivedHoldingSummaryResponse) validateHoldingSummary(formats strfmt.Registry) error {

	if swag.IsZero(m.HoldingSummary) { // not required
		return nil
	}

	for i := 0; i < len(m.HoldingSummary); i++ {
		if swag.IsZero(m.HoldingSummary[i]) { // not required
			continue
		}

		if m.HoldingSummary[i] != nil {
			if err := m.HoldingSummary[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("holdingSummary" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *DerivedHoldingSummaryResponse) validateLink(formats strfmt.Registry) error {

	if swag.IsZero(m.Link) { // not required
		return nil
	}

	if m.Link != nil {
		if err := m.Link.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("link")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *DerivedHoldingSummaryResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DerivedHoldingSummaryResponse) UnmarshalBinary(b []byte) error {
	var res DerivedHoldingSummaryResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
