// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// DetailCategory DetailCategory
// swagger:model DetailCategory
type DetailCategory struct {

	// The unique identifier of the detail category.<br><br><b>Applicable containers</b>: bill, creditCard, investment, insurance, loan<br>
	// Read Only: true
	ID int64 `json:"id,omitempty"`

	// The name of the detail category<br><br><b>Applicable containers</b>: bill, creditCard, investment, insurance, loan<br>
	// Read Only: true
	Name string `json:"name,omitempty"`
}

// Validate validates this detail category
func (m *DetailCategory) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DetailCategory) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DetailCategory) UnmarshalBinary(b []byte) error {
	var res DetailCategory
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
