// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// HoldingAssetClassificationListResponse HoldingAssetClassificationListResponse
// swagger:model HoldingAssetClassificationListResponse
type HoldingAssetClassificationListResponse struct {

	// asset classification list
	// Read Only: true
	AssetClassificationList []*AssetClassificationList `json:"assetClassificationList"`
}

// Validate validates this holding asset classification list response
func (m *HoldingAssetClassificationListResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAssetClassificationList(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HoldingAssetClassificationListResponse) validateAssetClassificationList(formats strfmt.Registry) error {

	if swag.IsZero(m.AssetClassificationList) { // not required
		return nil
	}

	for i := 0; i < len(m.AssetClassificationList); i++ {
		if swag.IsZero(m.AssetClassificationList[i]) { // not required
			continue
		}

		if m.AssetClassificationList[i] != nil {
			if err := m.AssetClassificationList[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("assetClassificationList" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *HoldingAssetClassificationListResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HoldingAssetClassificationListResponse) UnmarshalBinary(b []byte) error {
	var res HoldingAssetClassificationListResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
