// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ProviderAccountDetailResponse ProviderAccountDetailResponse
// swagger:model ProviderAccountDetailResponse
type ProviderAccountDetailResponse struct {

	// provider account
	// Read Only: true
	ProviderAccount []*ProviderAccountDetail `json:"providerAccount"`
}

// Validate validates this provider account detail response
func (m *ProviderAccountDetailResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateProviderAccount(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ProviderAccountDetailResponse) validateProviderAccount(formats strfmt.Registry) error {

	if swag.IsZero(m.ProviderAccount) { // not required
		return nil
	}

	for i := 0; i < len(m.ProviderAccount); i++ {
		if swag.IsZero(m.ProviderAccount[i]) { // not required
			continue
		}

		if m.ProviderAccount[i] != nil {
			if err := m.ProviderAccount[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("providerAccount" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ProviderAccountDetailResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProviderAccountDetailResponse) UnmarshalBinary(b []byte) error {
	var res ProviderAccountDetailResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
