// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TransactionCategoryResponse TransactionCategoryResponse
// swagger:model TransactionCategoryResponse
type TransactionCategoryResponse struct {

	// transaction category
	// Read Only: true
	TransactionCategory []*TransactionCategory `json:"transactionCategory"`
}

// Validate validates this transaction category response
func (m *TransactionCategoryResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTransactionCategory(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TransactionCategoryResponse) validateTransactionCategory(formats strfmt.Registry) error {

	if swag.IsZero(m.TransactionCategory) { // not required
		return nil
	}

	for i := 0; i < len(m.TransactionCategory); i++ {
		if swag.IsZero(m.TransactionCategory[i]) { // not required
			continue
		}

		if m.TransactionCategory[i] != nil {
			if err := m.TransactionCategory[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("transactionCategory" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *TransactionCategoryResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TransactionCategoryResponse) UnmarshalBinary(b []byte) error {
	var res TransactionCategoryResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
