// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TransactionCount TransactionCount
// swagger:model TransactionCount
type TransactionCount struct {

	// t o t a l
	TOTAL *TransactionTotal `json:"TOTAL,omitempty"`
}

// Validate validates this transaction count
func (m *TransactionCount) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTOTAL(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TransactionCount) validateTOTAL(formats strfmt.Registry) error {

	if swag.IsZero(m.TOTAL) { // not required
		return nil
	}

	if m.TOTAL != nil {
		if err := m.TOTAL.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("TOTAL")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TransactionCount) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TransactionCount) UnmarshalBinary(b []byte) error {
	var res TransactionCount
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
