// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// TransactionCategoryRequest TransactionCategoryRequest
// swagger:model TransactionCategoryRequest
type TransactionCategoryRequest struct {

	// category name
	CategoryName string `json:"categoryName,omitempty"`

	// parent category Id
	// Required: true
	ParentCategoryID *int32 `json:"parentCategoryId"`

	// source
	// Read Only: true
	Source string `json:"source,omitempty"`
}

// Validate validates this transaction category request
func (m *TransactionCategoryRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateParentCategoryID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TransactionCategoryRequest) validateParentCategoryID(formats strfmt.Registry) error {

	if err := validate.Required("parentCategoryId", "body", m.ParentCategoryID); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TransactionCategoryRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TransactionCategoryRequest) UnmarshalBinary(b []byte) error {
	var res TransactionCategoryRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
