// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// TransactionDays TransactionDays
// swagger:model TransactionDays
type TransactionDays struct {

	// number of transaction days
	NumberOfTransactionDays int32 `json:"numberOfTransactionDays,omitempty"`
}

// Validate validates this transaction days
func (m *TransactionDays) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TransactionDays) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TransactionDays) UnmarshalBinary(b []byte) error {
	var res TransactionDays
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
