// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TransactionCategorizationRule TransactionCategorizationRule
// swagger:model TransactionCategorizationRule
type TransactionCategorizationRule struct {

	// The level of the category for which the rule is created.<br><br><b>Applicable containers</b>: bill, creditCard, insurance, loan<br>
	// Read Only: true
	CategoryLevelID int32 `json:"categoryLevelId,omitempty"`

	// Unique identifier of the user.<br><br><b>Applicable containers</b>: bill, creditCard, investment, insurance, loan<br>
	// Read Only: true
	MemID int64 `json:"memId,omitempty"`

	// Details of rules. <br><br><b>Applicable containers</b>: bill, creditCard, investment, insurance, loan<br>
	// Read Only: true
	RuleClauses []*RuleClause `json:"ruleClauses"`

	// The order in which the rules get executed on transactions.<br><br><b>Applicable containers</b>: bill, creditCard, investment, insurance, loan<br>
	// Read Only: true
	RulePriority int32 `json:"rulePriority,omitempty"`

	// Category id that is assigned to the transaction when the transaction matches the rule clause. This is the id field of the transaction category resource.<br><br><b>Applicable containers</b>: bill, creditCard, investment, insurance, loan<br>
	// Read Only: true
	TransactionCategorisationID int64 `json:"transactionCategorisationId,omitempty"`

	// Unique identifier generated for every rule the user creates.<br><br><b>Applicable containers</b>: bill, creditCard, investment, insurance, loan<br>
	// Read Only: true
	UserDefinedRuleID int64 `json:"userDefinedRuleId,omitempty"`
}

// Validate validates this transaction categorization rule
func (m *TransactionCategorizationRule) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRuleClauses(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TransactionCategorizationRule) validateRuleClauses(formats strfmt.Registry) error {

	if swag.IsZero(m.RuleClauses) { // not required
		return nil
	}

	for i := 0; i < len(m.RuleClauses); i++ {
		if swag.IsZero(m.RuleClauses[i]) { // not required
			continue
		}

		if m.RuleClauses[i] != nil {
			if err := m.RuleClauses[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("ruleClauses" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *TransactionCategorizationRule) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TransactionCategorizationRule) UnmarshalBinary(b []byte) error {
	var res TransactionCategorizationRule
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
